### ISSUE TITLE
Better results when I having reimplement the "2D_FFTs" convolution with PyTorch

### ISSUE THREAD

**Issue by songyuc** [sascha-kirch/ML_Notebooks#1]
Hi, Sascha,
Appreciate very much your great work on the blog of "Fourier Convolutions with Kernel Sizes of 1024x1024 and Larger"!
I have got better results after reimplementing the "2D_FFTs" convolution with PyTorch, as,
```bash
Mean Absolute Error: 6.840202217972546e-07
Standard deviation: 6.106938030825404e-07
```
Thank you again for a lot of knowledge learned from your blog!

**Comment by sascha-kirch** [comment]
Hi songyuc,
happy to hear that the article motivated you to implement it yourself!

Great results! The errors in both cases are very small and caused by the quntazition of values stored on the computer. Probably in pytorch you required less commands to implement the fourier convolution or used a datatype with higher accuracy.

All the best,
Sascha
